
version: "3.4"

services:
  # postgres:
  #   image: postgres:10
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: testuser
  #     POSTGRES_PASSWORD: testpass
  #     POSTGRES_DB: an_app
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
